// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuantAgent.API.Data;

#nullable disable

namespace QuantAgent.API.Migrations
{
    [DbContext(typeof(QuantDbContext))]
    [Migration("20260606140206_AddApiKeysTable")]
    partial class AddApiKeysTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuantAgent.API.Models.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Deporte")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("deporte");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<int>("Exitos")
                        .HasColumnType("integer")
                        .HasColumnName("exitos");

                    b.Property<int>("Fallos")
                        .HasColumnType("integer")
                        .HasColumnName("fallos");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("key");

                    b.Property<DateTime>("UltimoUso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_uso");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Deporte")
                        .HasDatabaseName("ix_api_keys_deporte");

                    b.HasIndex("Estado")
                        .HasDatabaseName("ix_api_keys_estado");

                    b.ToTable("api_keys", (string)null);
                });

            modelBuilder.Entity("QuantAgent.API.Models.Partido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EquipoLocal")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("equipo_local");

                    b.Property<string>("EquipoVisitante")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("equipo_visitante");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<int?>("FixtureId")
                        .HasColumnType("integer");

                    b.Property<int?>("GolesLocal")
                        .HasColumnType("integer")
                        .HasColumnName("goles_local");

                    b.Property<int?>("GolesVisitante")
                        .HasColumnType("integer")
                        .HasColumnName("goles_visitante");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("ix_partidos_estado");

                    b.HasIndex("FechaInicio")
                        .HasDatabaseName("ix_partidos_fecha_inicio");

                    b.ToTable("partidos", (string)null);
                });

            modelBuilder.Entity("QuantAgent.API.Models.Prediccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Confianza")
                        .HasColumnType("integer")
                        .HasColumnName("confianza");

                    b.Property<decimal>("CornersOverUnder")
                        .HasColumnType("numeric(5,1)")
                        .HasColumnName("corners_over_under");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Cuota")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("cuota");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<int>("Mercado")
                        .HasColumnType("integer")
                        .HasColumnName("mercado");

                    b.Property<Guid>("PartidoId")
                        .HasColumnType("uuid")
                        .HasColumnName("partido_id");

                    b.Property<string>("Razonamiento")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("razonamiento");

                    b.Property<string>("Seleccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("seleccion");

                    b.Property<decimal>("TotalGoals")
                        .HasColumnType("numeric(5,1)")
                        .HasColumnName("total_goals");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("ix_predicciones_estado");

                    b.HasIndex("PartidoId")
                        .HasDatabaseName("ix_predicciones_partido_id");

                    b.ToTable("predicciones", (string)null);
                });

            modelBuilder.Entity("QuantAgent.API.Models.ReglaAprendida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Contexto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("contexto");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Equipo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("equipo");

                    b.Property<int>("Peso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("peso");

                    b.Property<Guid?>("PrediccionId")
                        .HasColumnType("uuid")
                        .HasColumnName("prediccion_id");

                    b.Property<string>("Regla")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("regla");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Equipo")
                        .HasDatabaseName("ix_reglas_aprendidas_equipo");

                    b.HasIndex("PrediccionId")
                        .HasDatabaseName("ix_reglas_aprendidas_prediccion_id");

                    b.ToTable("reglas_aprendidas", (string)null);
                });

            modelBuilder.Entity("QuantAgent.API.Models.Prediccion", b =>
                {
                    b.HasOne("QuantAgent.API.Models.Partido", "Partido")
                        .WithMany()
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partido");
                });

            modelBuilder.Entity("QuantAgent.API.Models.ReglaAprendida", b =>
                {
                    b.HasOne("QuantAgent.API.Models.Prediccion", "Prediccion")
                        .WithMany()
                        .HasForeignKey("PrediccionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Prediccion");
                });
#pragma warning restore 612, 618
        }
    }
}
